### PR TITLE
bounded gap affine WFA

### PR DESCRIPTION
**Pull request by ekg**
When building in a guix container, I continued to have problems with the Makefile. It appears that somehow the recursive make was not working in my build context.

This resolves them. It is very verbose. And, it only compiles libwfa, which is probably not desirable.

### CODE REVIEW

**Comment by smarco** [comment]
Ok, can you share the error you are getting so I can understand which race-condition or problem we are facing? Thanks,

**Comment by ekg** [comment]
This adds a CMakeLitst.txt and a bounded WFA algorithm where a max_score can be set to limit compute time.

**Comment by ekg** [comment]
When using cmake, we can include WFA in a project with this addition to its CMakeLists.txt:

```
add_subdirectory(deps/WFA EXCLUDE_FROM_ALL)
```

**Comment by smarco** [comment]
Hi, @ekg 

Is this still an issue with the current HEAD? I no longer get an error when make-ing with multiple threads

> make -j 20

Let me know so I can take action.
Thank you in advance.

Best,

**Comment by ekg** [comment]
I'm still using the cmakelists in my branch and forks, so i don't know.
I'll check and let you know.

**Comment by ekg** [comment]
This isn't to merge... and feel free to close this. It's pegged to the master of my fork so it keeps getting updated as I develop there. It might be interesting to cherry-pick from.

I've added a bounded version of the gap affine alignment, which has a maximum score, so as to short-circuit alignment when it goes beyond a given score.

This also builds with cmake, and renames and moves all the files around. It's a C++-ification of WFA. I wouldn't merge it.

**Comment by smarco** [comment]
No, but these are features/additions that should be present in the next release of the WFA.
I am currently working on it, so I should be able to integrate them easily.

Thanks,

**Pull request closed without merging**
